name:                dta-tool
version:             0.1.0.0
github:              "githubuser/dta-tool"
license:             BSD3
author:              "Andrew Russell"
maintainer:          "andrew.russell001[at]gmail.com"
copyright:           "2019 Andrew Russell"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dta-tool#readme>

dependencies:
- base >= 4.7 && < 5
- language-c >= 0.8.2
- pretty-show >= 1.9.5
- pretty >= 1.1.3.6
- containers >= 0.6.0.1

library:
  source-dirs: src

executables:
  dta-tool-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dta-tool

tests:
  dta-tool-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dta-tool
